{
 "title": "Triton Inference Server",
 "description": "Nvidia Triton inference server metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "nv_cpu_utilization", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Count of Inference Failures",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "nv_inference_request_failure{job=\"triton-server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Used in MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nv_cpu_memory_used_bytes / 1000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "{job=\"triton-server\"} |= `level=error`"
    }
   ]
  },
  {
   "title": "Cumulative Inference Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "nv_inference_request_success", "legendFormat": "Success {{instance}}" },
    { "expr": "nv_inference_request_failure", "legendFormat": "Failure {{instance}}" }
   ]
  },
  {
   "title": "logs",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "{job=\"triton-server\"}"
    }
   ]
  },
  {
   "title": "Queue Time (milliseconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(nv_inference_queue_duration_us[30s]) / 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}